djcrm/urls.py
from os import stat
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from leads.views import landing, LandingPageView, SignupView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace="leads")),
    path('agents/', include('agents.urls', namespace="agents")),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('signup/', SignupView.as_view(), name='signup'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import *

app_name = 'leads'

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-details'),
    path('<int:pk>/update', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent', AssignAgentView.as_view(), name='assign-agent'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(),
         name='category-detail'),
    path('<int:pk>/categories/', LeadCategoryUpdateView.as_view(),
         name='category-update'),
    path('categories', CategoryListView.as_view(), name='category-list')

]

leads/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.fields.related import OneToOneField
from django.db.models.signals import post_save
# Create your models here.


class User(AbstractUser):
    is_organizer = models.BooleanField(default=True)
    is_agent = models.BooleanField(default=False)


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Lead(models.Model):
    first_name = models.CharField(max_length=25)
    last_name = models.CharField(max_length=25)
    age = models.IntegerField(default=0)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    agent = models.ForeignKey(
        "Agent", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey(
        'Category', null=True, blank=True, related_name='leads', on_delete=models.SET_NULL)
    description = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Agent(models.Model):
    user = OneToOneField(User, on_delete=models.CASCADE)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email


class Category(models.Model):
    name = models.CharField(max_length=30)
    organization = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)


post_save.connect(post_user_created_signal, sender=User)

leads/forms.py
from django.http import request
from leads.models import Lead
from django import forms
from .models import Agent, Lead, User
from django.contrib.auth.forms import UserCreationForm, UsernameField
from django.contrib.auth import get_user_model

User = get_user_model()


class LeadFormModel(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
            'description',
            'phone_number',
            'email',
        )


class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}


class AssignAgentForm(forms.Form):
    agent = forms.ModelChoiceField(queryset=Agent.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop('request')
        agents = Agent.objects.filter(organization=request.user.userprofile)
        super(AssignAgentForm, self).__init__(*args, **kwargs)
        self.fields['agent'].queryset = agents


class LeadCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'category',
        )

leads/views.py
from django.db.models.query import QuerySet
from django.http import request
from django.shortcuts import redirect, render, reverse
from django.core.mail import send_mail
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.views.generic.edit import UpdateView
from .models import Lead, Category
from agents.mixins import OrganizerandLoginRequiredMixin
from .forms import LeadFormModel, CustomUserCreationForm, AssignAgentForm, LeadCategoryUpdateForm
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, DeleteView
from django.contrib import messages

# Create your views here.


class SignupView(generic.CreateView):
    template_name = 'registration/signup.html'
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")


class LandingPageView(TemplateView):
    template_name = 'landing.html'


def landing(request):
    return render(request, 'landing.html')


class LeadListView(LoginRequiredMixin, ListView):
    template_name = 'leads/home_page.html'
    context_object_name = 'leads'

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile, agent__isnull=False)
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization, agent__isnull=False)
            queryset = queryset.filter(agent__user=user)

        return queryset

    def get_context_data(self, **kwargs):
        context = super(LeadListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile,
                                           agent__isnull=True)

            context.update({
                'unassigned_leads': queryset,
            })

        return context


def home(request):
    lead = Lead.objects.all()
    context = {'leads': lead}
    return render(request, 'leads/home_page.html', context=context)


class LeadDetailView(LoginRequiredMixin, DetailView):
    template_name = 'leads/lead_detail.html'
    context_object_name = 'lead'

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            queryset = Lead.objects.filter(organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(organization=user.agent.userprofile)
            queryset = queryset.filter(agent__user=user)

        return queryset


def lead_details(request, pk):
    lead = Lead.objects.get(id=pk)
    context = {
        'lead': lead
    }

    return render(request, 'leads/lead_detail.html', context=context)


class LeadCreateView(OrganizerandLoginRequiredMixin, CreateView):
    template_name = 'leads/create_lead.html'
    form_class = LeadFormModel

    def get_success_url(self):
        return reverse("leads:lead-list")

    def form_valid(self, form):
        lead = form.save(commit=False)
        lead.organization = self.request.user.userprofile

        lead.save()
        send_mail(
            subject="Creted a new lead",
            message="new lead created",
            from_email='test@test.com',
            recipient_list=['test2@test.com']
        )
        messages.success(self.request, "You have successfully created a lead")
        return super(LeadCreateView, self).form_valid(form)


def create(request):
    form = LeadFormModel()

    if request.method == "POST":
        form = LeadFormModel(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/leads')

    context = {
        'form': form
    }

    return render(request, 'leads/create_lead.html', context=context)


class LeadUpdateView(OrganizerandLoginRequiredMixin, UpdateView):
    template_name = 'leads/lead_update.html'
    form_class = LeadFormModel

    def get_queryset(self):
        user = self.request.user

        return Lead.objects.filter(organization=user.userprofile)

    def get_success_url(self):
        return reverse("leads:lead-list")


def update(request, pk):
    lead = Lead.objects.get(id=pk)
    form = LeadFormModel(instance=lead)

    if request.method == "POST":
        form = LeadFormModel(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect(f'/leads/{pk}')

    context = {
        'lead': lead,
        'form': form
    }

    return render(request, 'leads/lead_update.html', context=context)


class LeadDeleteView(OrganizerandLoginRequiredMixin, DeleteView):
    template_name = 'leads/lead_delete.html'

    def get_queryset(self):
        user = self.request.user

        return Lead.objects.filter(organization=user.userprofile)

    def get_success_url(self):
        return reverse("leads:lead-list")


def delete(request, pk):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect('/leads')


class AssignAgentView(OrganizerandLoginRequiredMixin, generic.FormView):
    template_name = 'leads/assign-agent.html'
    
    form_class = AssignAgentForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignAgentView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            'request': self.request,
        })
        return kwargs

    def get_success_url(self):
        return reverse('leads:lead-list')

    def form_valid(self, form):
        agent = form.cleaned_data['agent']
        lead = Lead.objects.get(id=self.kwargs["pk"])
        lead.agent = agent
        lead.save()

        return super(AssignAgentView, self).form_valid(form)


class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = 'leads/category_list.html'
    context_object_name = 'category_list'

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile, )
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization)

        context.update({
            'unassigned_lead_count': queryset.filter(category__isnull=True).count()
        })

        return context

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            queryset = Category.objects.filter(
                organization=user.userprofile)
        else:
            queryset = Category.objects.filter(
                organization=user.agent.organization)

        return queryset


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = 'leads/category-detail.html'
    context_object_name = 'category'

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            queryset = Category.objects.filter(
                organization=user.userprofile)
        else:
            queryset = Category.objects.filter(
                organization=user.agent.organization)

        return queryset


class LeadCategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    template_name = 'leads/lead-category-update.html'
    form_class = LeadCategoryUpdateForm

    def get_queryset(self):
        user = self.request.user

        if user.is_organizer:
            queryset = Lead.objects.filter(
                organization=user.userprofile)
        else:
            queryset = Lead.objects.filter(
                organization=user.agent.organization)
            queryset = queryset.filter(agent__user=user)

        return queryset

    def get_success_url(self):
        return reverse('leads:lead-details', kwargs={"pk": self.get_object().id})

# def create(request):
#     form = LeadForm()

#     if request.method == "POST":
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             agent = Agent.objects.first()

#             Lead.objects.create(
#                 first_name=first_name,
#                 last_name=last_name,
#                 age=age,
#                 agent=agent,
#             )
#             return redirect('/leads')

#     context = {
#         'form': form
#     }

#     return render(request, 'leads/create_lead.html', context=context)


# def create(request):
#     form = LeadForm()

#     if request.method == "POST":
#         form = LeadForm(request.POST)
#         if form.is_valid():
#             first_name = form.cleaned_data['first_name']
#             last_name = form.cleaned_data['last_name']
#             age = form.cleaned_data['age']
#             agent = Agent.objects.first()

#             Lead.objects.create(
#                 first_name=first_name,
#                 last_name=last_name,
#                 age=age,
#                 agent=agent,
#             )
#             return redirect('/leads')

#     context = {
#         'form': form
#     }

#     return render(request, 'leads/create_lead.html', context=context)

leads/templates/leads/category_list.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">
    <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
            <h1 class="sm:text-4xl text-3xl font-medium title-font mb-2 text-gray-900">Categories</h1>
            <p class="lg:w-2/3 mx-auto leading-relaxed text-base">Categories for Leads</p>
        </div>
        <div class="lg:w-2/3 w-full mx-auto overflow-auto">
            <table class="table-auto w-full text-left whitespace-no-wrap">
                <thead>
                    <tr>
                        <th
                            class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100 rounded-tl rounded-bl">
                            Name</th>
                        <th class="px-4 py-3 title-font tracking-wider font-medium text-gray-900 text-sm bg-gray-100">
                            Lead Count</th>

                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td class="px-4 py-3">Unassigned</td>
                        <td class="px-4 py-3">{{unassigned_lead_count}}</td>
                    </tr>
                    {% for category in category_list %}
                    <tr>
                        <td class="px-4 py-3">
                            <a href="{% url 'leads:category-detail' category.pk %}">
                                {{category.name}}
                            </a>
                        </td>
                        <td class="px-4 py-3">TODO Count</td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>

    </div>
</section>

{% endblock content %}

leads/templates/leads/home_page.html
{% extends 'base.html' %}

{% block content %}


<section class="text-gray-600 body-font">

    <div class="container px-5 py-24 mx-auto flex flex-wrap">

        <div class="mb-6 py-6">

            <div>

                <h1 class="text-4xl">Leads</h1>
            </div>
            {% if request.user.is_organizer %}
            <div class="mt-10">
                <button
                    class="inline-flex items-center bg-gray-100 mr-5 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 hover:text-black rounded text-base mt-4 md:mt-0 bg-indigo-500 text-white">

                    <a href="{% url 'leads:lead-create' %}" class="hover:text-indigo-500">
                        <h2>Create a new lead</h2>
                    </a>

                </button>
            </div>
            <div class="mt-3">
                <a href="{% url 'leads:category-list' %}">Go to categories</a>
            </div>
            {% endif %}
        </div>
        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                        <table class="min-w-full divide-y divide-gray-200">
                            <thead class="bg-gray-50">
                                <tr>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        First Name
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Last Name
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Age
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Email
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Cell Phone Number
                                    </th>
                                    <th scope="col"
                                        class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                        Category
                                    </th>
                                    <th scope="col" class="relative px-6 py-3">
                                        <span class="sr-only">Edit</span>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for lead in leads %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        <a class="text-blue-500 hover:text-blue-800"
                                            href="{% url 'leads:lead-details' lead.pk %}">{{ lead.first_name }}</a>
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ lead.last_name }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ lead.age }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ lead.email }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ lead.phone_number }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap">
                                        {% if lead.category %}
                                        <span
                                            class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                            {{ lead.category.name }}
                                        </span>
                                        {% else %}
                                        <span
                                            class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                                            Unassigned
                                        </span>
                                        {% endif %}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'leads:lead-update' lead.pk %}"
                                            class="text-indigo-600 hover:text-indigo-900">
                                            Edit
                                        </a>
                                    </td>
                                </tr>

                                {% empty %}

                                <p>There are currently no leads</p>

                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="mt-4 flex flex-wrap -m-4">

            {% if unassigned_leads.exists %}
            <div class="p-4 w-full">
                <h1 class="text-4xl">Unassigned Leads</h1>
            </div>

            {% for lead in unassigned_leads %}
            <div class="p-4 lg:w-1/2 md:w-full">

                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                    <div
                        class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                            <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                        </svg>
                    </div>

                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{lead.first_name}}
                            {{lead.last_name}}
                        </h2>
                        <p class="leading-relaxed text-base">{{lead.description}}</p>
                        <a href="{% url 'leads:assign-agent' lead.pk %}"
                            class="mt-3 text-indigo-500 inline-flex items-center">Assign this lead to an agent
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>

            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>

    </div>
</section>
{% endblock content %}

leads/templates/leads/lead-category-update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-full mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'leads:lead-details' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
                    <a href="{% url 'leads:category-update' lead.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Category</a>
                    <a href="{% url 'leads:lead-update' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update
                        Details</a>
                </div>
                <div class="max-w-lg mx-auto">
                    <form method="POST">
                        {% csrf_token %}
                        {{form|crispy}}

                        <button type="submit"
                            class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white">Update</button>
                    </form>



                </div>
                <div class="py-5 border-t  border-gray-200 mt-5">
                    <a href="{% url 'leads:lead-delete' lead.pk %}">

                        <button
                            class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</button>
                    </a>
                </div>
            </div>
            <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero"
                src="https://cdn.pixabay.com/photo/2015/10/31/11/59/business-card-1015284_960_720.jpg">
        </div>
    </div>
</section>

{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends 'base.html' %}

{% block content %}




<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-full mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Description</a>
                    <a href="{% url 'leads:category-update' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
                    <a href="{% url 'leads:lead-update' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Details</a>
                </div>
                <p class="leading-relaxed mb-4">{{lead.description}}</p>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Age</span>
                    <span class="ml-auto text-gray-900">{{lead.age}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900">{{lead.email}}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                    <span class="text-gray-500">Phone Number</span>
                    <span class="ml-auto text-gray-900">{{lead.phone_number}}</span>
                </div>
                <div class="flex">
                    <a href="{% url 'leads:lead-delete' lead.pk %}">
                        <button
                            class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</button>
                    </a>
                </div>
            </div>
            <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero"
                src="https://cdn.pixabay.com/photo/2015/10/31/11/59/business-card-1015284_960_720.jpg">
        </div>
    </div>
</section>










{% endblock content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-full mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">LEAD</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{lead.first_name}} {{lead.last_name}}
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'leads:lead-details' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Description</a>
                    <a href="{% url 'leads:category-update' lead.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Category</a>
                    <a href="{% url 'leads:lead-update' lead.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update
                        Details</a>
                </div>
                <div class="max-w-lg mx-auto">
                    <form method="POST">
                        {% csrf_token %}
                        {{form|crispy}}

                        <button type="submit"
                            class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white">Update</button>
                    </form>



                </div>
                <div class="py-5 border-t  border-gray-200 mt-5">
                    <a href="{% url 'leads:lead-delete' lead.pk %}">

                        <button
                            class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</button>
                    </a>
                </div>

            </div>
            <img class="lg:w-3/6 md:w-2/6 w-1/6 mb-10 object-contain object-center rounded" alt="hero"
                src="https://cdn.pixabay.com/photo/2015/10/31/11/59/business-card-1015284_960_720.jpg">
        </div>
    </div>
</section>

{% endblock content %}