agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete', AgentDeleteView.as_view(), name='agent-delete'),
]

djcrm/urls.py
from os import stat
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from leads.views import landing, LandingPageView, SignupView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace="leads")),
    path('agents/', include('agents.urls', namespace="agents")),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('signup/', SignupView.as_view(), name='signup'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = {
            'email',
            'username',
            'first_name',
            'last_name'
        }

agents/views.py
from django.db import models
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .mixins import OrganizerandLoginRequiredMixin
from leads.models import Agent
from django.shortcuts import reverse
from .forms import AgentModelForm, User
from django.core.mail import send_mail
import random


class AgentListView(OrganizerandLoginRequiredMixin, generic.ListView):
    template_name = 'agents/agent-list.html'

    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)


class AgentCreateView(OrganizerandLoginRequiredMixin, generic.CreateView):
    template_name = 'agents/agent-create.html'
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agents:agent-list')

    def form_valid(self, form):
        user = form.save()
        user.is_agent = True
        user.is_organizer = False
        user.set_password(f"{random.randint(0, 100000)}")
        user.save()
        Agent.objects.create(
            user=user,
            organization=self.request.user.userprofile
        )
        send_mail(
            subject="You have been added as an agent",
            message="Login to your account and start working as an agent on DJCRM",
            from_email='admin@djcrm.com',
            recipient_list=[user.email]

        )

        # agent.organization = self.request.user.userprofile
        # agent.save()
        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(OrganizerandLoginRequiredMixin, generic.DetailView):
    template_name = 'agents/agent-detail.html'
    context_object_name = 'agent'

    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)


class AgentUpdateView(OrganizerandLoginRequiredMixin, generic.UpdateView):
    template_name = 'agents/agent-update.html'
    form_class = AgentModelForm

    def get_queryset(self):
        user = self.request.user
        return Agent.objects.filter(organization=user.userprofile)

    def get_success_url(self):
        return reverse('agents:agent-list')


class AgentDeleteView(OrganizerandLoginRequiredMixin, generic.DeleteView):
    template_name = 'agents/agent-delete.html'
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse('agents:agent-list')

    def get_queryset(self):
        organization = self.request.user.userprofile
        return Agent.objects.filter(organization=organization)

agents/templates/agents/agent-create.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <h1 class="text-4xl text-gray-800 mb-5">Create a new Agent</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white"> Create
            Agent
        </button>


    </form>
    <div class="py-5 border-t  border-gray-200 mt-5">
        <a class="hover:text-blue-500 mt-3" href="{% url 'agents:agent-list' %}">Back To Agents</a>

    </div>
</div>

{% endblock content %}

agents/templates/agents/agent-delete.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <h1 class="text-4xl text-gray-800 mb-5">Are you sure you want to delete {{agent.user.username}}?</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white"> Delete
        </button>


    </form>
    <div class="py-5 border-t  border-gray-200 mt-5">
        <a class="hover:text-blue-500 mt-3" href="{% url 'agents:agent-detail' agent.pk %}">Back To
            {{agent.user.username}}</a>

    </div>
</div>

{% endblock content %}

agents/templates/agents/agent-detail.html
{% extends 'base.html' %}

{% block content %}




<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-full mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}}
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'agents:agent-detail' agent.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>

                    <a href="{% url 'agents:agent-update' agent.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Details</a>
                </div>

                <div class="flex py-2">
                    <span class="text-gray-500">Date Joined</span>
                    <span class="ml-auto text-gray-900">{{agent.user.date_joined}}</span>
                </div>
                <div class="flex border-t border-gray-200 py-2">
                    <span class="text-gray-500">Email</span>
                    <span class="ml-auto text-gray-900">{{agent.user.email}}</span>
                </div>
                <div class="flex border-t border-b mb-6 border-gray-200 py-2">
                    <span class="text-gray-500">Organization</span>
                    <span class="ml-auto text-gray-900">{{agent.organization}}</span>
                </div>
                <div class="flex">
                    <a href="{% url 'agents:agent-delete' agent.pk %}">
                        <button
                            class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</button>
                    </a>
                </div>
            </div>
            <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero"
                src="https://cdn.pixabay.com/photo/2018/02/02/17/28/key-3125904_960_720.jpg">
        </div>
    </div>
</section>





{% endblock content %}

agents/templates/agents/agent-list.html
{% extends 'base.html' %}

{% block content %}
<section class="text-gray-600 body-font">

    <div class="container px-5 py-24 mx-auto flex flex-wrap">

        <div class="mb-6 py-6">

            <div>

                <h1 class="text-4xl">Agents</h1>
            </div>

            <div class="mt-10">
                <button
                    class="inline-flex items-center bg-gray-100 mr-5 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 hover:text-black rounded text-base mt-4 md:mt-0 bg-indigo-500 text-white">

                    <a href="{% url 'agents:agent-create' %}" class="hover:text-indigo-500">
                        <h2>Create a new Agent</h2>
                    </a>
                </button>
            </div>

        </div>

        <div class="flex flex-wrap-m-4 p-4 w-full">
            {% for agent in object_list %}
            <div class="p-4 lg:w-1/2 md:w-full">

                <div class="flex border-2 rounded-lg border-gray-200 border-opacity-50 p-8 sm:flex-row flex-col">
                    <div
                        class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                        <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                            stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                            <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                        </svg>
                    </div>

                    <div class="flex-grow">
                        <h2 class="text-gray-900 text-lg title-font font-medium mb-3">{{agent.user.username}}
                        </h2>
                        <p class="leading-relaxed text-base">Click on the below link to get the details of the agent
                            <span class="font-semibold">
                                {{agent.user.username}}
                            </span>
                        </p>
                        <a href="{% url 'agents:agent-detail' agent.pk %}"
                            class="mt-3 text-indigo-500 inline-flex items-center">View
                            This Agent
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                                stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                <path d="M5 12h14M12 5l7 7-7 7"></path>
                            </svg>
                        </a>
                    </div>
                </div>

            </div>
            {% endfor %}
        </div>
    </div>

    </div>
</section>
{% endblock content %}

agents/templates/agents/agent-update.html
{% extends 'base.html' %}
{% load tailwind_filters %}

{% block content %}
<section class="text-gray-600 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
        <div class="lg:w-full mx-auto flex flex-wrap">
            <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
                <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
                <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{agent.user.username}}
                </h1>
                <div class="flex mb-4">
                    <a href="{% url 'agents:agent-detail' agent.pk %}"
                        class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Overview</a>

                    <a href="{% url 'agents:agent-update' agent.pk %}"
                        class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Update
                        Details</a>
                </div>
                <div class="max-w-lg mx-auto">
                    <form method="POST">
                        {% csrf_token %}
                        {{form|crispy}}

                        <button type="submit"
                            class="w-full bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md text-white">Update</button>
                    </form>



                </div>
                <div class="py-5 border-t  border-gray-200 mt-5">
                    <a href="{% url 'agents:agent-delete' agent.pk %}">

                        <button
                            class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Delete</button>
                    </a>
                </div>

            </div>
            <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero"
                src="https://cdn.pixabay.com/photo/2018/02/02/17/28/key-3125904_960_720.jpg">
        </div>
    </div>
</section>

{% endblock content %}