agents/urls.py
from django.urls import path
from .views import AgentListView, AgentCreateView, AgentDetailView, AgentUpdateView, AgentDeleteView

app_name = 'agents'

urlpatterns = [
    path('', AgentListView.as_view(), name='agent-list'),
    path('create/', AgentCreateView.as_view(), name='agent-create'),
    path('<int:pk>/', AgentDetailView.as_view(), name='agent-detail'),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
    path('<int:pk>/delete', AgentDeleteView.as_view(), name='agent-delete'),
]

djcrm/urls.py
from os import stat
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from leads.views import landing, LandingPageView, SignupView
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('leads/', include('leads.urls', namespace="leads")),
    path('agents/', include('agents.urls', namespace="agents")),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('reset-password/', PasswordResetView.as_view(), name='reset-password'),
    path('password-reset-done/', PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>', PasswordResetConfirmView.as_view(),
         name='password_reset_confirm'),
    path('password-reset-complete/', PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),
    path('signup/', SignupView.as_view(), name='signup'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

leads/urls.py
from django.urls import path
from .views import *

app_name = 'leads'

urlpatterns = [
    path('', LeadListView.as_view(), name='lead-list'),
    path('create/', LeadCreateView.as_view(), name='lead-create'),
    path('<int:pk>/', LeadDetailView.as_view(), name='lead-details'),
    path('<int:pk>/update', LeadUpdateView.as_view(), name='lead-update'),
    path('<int:pk>/delete', LeadDeleteView.as_view(), name='lead-delete'),
    path('<int:pk>/assign-agent', AssignAgentView.as_view(), name='assign-agent'),
    path('categories/<int:pk>/', CategoryDetailView.as_view(),
         name='category-detail'),
    path('<int:pk>/categories/', LeadCategoryUpdateView.as_view(),
         name='category-update'),
    path('categories', CategoryListView.as_view(), name='category-list')

]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>DJCRM</title>
    <link rel="icon" type="image/svg+xml"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%22256%22 height=%22256%22 viewBox=%220 0 100 100%22><rect width=%22100%22 height=%22100%22 rx=%2250%22 fill=%22%235757bd%22></rect><path d=%22M55.18 42.84L55.18 42.84Q55.18 37.08 53.42 32.99Q51.66 28.89 48.65 26.28Q45.63 23.67 41.63 22.46Q37.63 21.24 33.04 21.24L33.04 21.24Q30.16 21.24 28.04 21.42Q25.92 21.60 24.13 21.96L24.13 21.96L24.13 64.80Q26.29 65.34 28.76 65.52Q31.23 65.70 33.84 65.70L33.84 65.70Q44.47 65.70 49.82 59.94Q55.18 54.18 55.18 42.84ZM62.65 42.84L62.65 42.84Q62.65 50.22 60.62 55.67Q58.59 61.11 54.86 64.71Q51.13 68.31 45.82 70.07Q40.51 71.82 33.94 71.82L33.94 71.82Q31.05 71.82 27.45 71.60Q23.86 71.38 20.62 70.38L20.62 70.38Q16.84 69.21 16.84 66.24L16.84 66.24L16.84 19.98Q16.84 18.54 17.55 17.78Q18.27 17.01 19.80 16.56L19.80 16.56Q22.59 15.66 26.11 15.39Q29.62 15.12 33.13 15.12L33.13 15.12Q39.70 15.12 45.14 16.88Q50.59 18.63 54.45 22.10Q58.33 25.56 60.48 30.74Q62.65 35.91 62.65 42.84ZM68.05 83.97L68.05 83.97Q69.66 83.25 70.97 82.49Q72.27 81.72 73.13 80.60Q73.98 79.47 74.48 77.81Q74.97 76.14 74.97 73.53L74.97 73.53L74.97 29.43Q75.42 29.25 76.37 29.03Q77.31 28.80 78.39 28.80L78.39 28.80Q82.17 28.80 82.17 32.13L82.17 32.13L82.17 74.88Q82.17 78.84 81.09 81.41Q80.02 83.97 78.44 85.55Q76.86 87.13 75.16 87.75Q73.44 88.38 72.19 88.38L72.19 88.38Q69.94 88.38 69.08 87.08Q68.22 85.77 68.05 83.97ZM73.89 16.11L73.89 16.11Q73.89 14.22 75.20 12.92Q76.50 11.61 78.57 11.61L78.57 11.61Q80.64 11.61 81.91 12.92Q83.16 14.22 83.16 16.11L83.16 16.11Q83.16 18.00 81.91 19.31Q80.64 20.61 78.57 20.61L78.57 20.61Q76.50 20.61 75.20 19.31Q73.89 18.00 73.89 16.11Z%22 fill=%22%23fff%22></path></svg>" />
    <link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">


</head>


<body>
    <div class="max-w-5xl mx-auto">
        <div style="min-height: 90vh;">
            {% include 'navbar.html' %}
            {% block content %}
            {% endblock content %}
        </div>
        {% include 'footer.html' %}
    </div>

</body>

</html>

templates/landing.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<section class="text-gray-600 body-font">
    <div class="container mx-auto flex px-5 py-24 items-center justify-center flex-col">
        <img class="lg:w-2/6 md:w-3/6 w-5/6 mb-10 object-cover object-center rounded" alt="hero"
            src="{% static 'images/dashboard.png' %}">
        <div class="text-center lg:w-2/3 w-full">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
                {% if request.user.is_authenticated %}
                Logged in as {{request.user.username}}
                {%else%}
                Django CRM
                {% endif %}
            </h1>

            <p class="mb-8 leading-relaxed">Made with <span style="color: #e25555;">&#9829;</span> Using Django</p>

            <div class="flex justify-center">
                {% if request.user.is_authenticated %}
                <a href="{% url 'leads:lead-list' %}">
                    <button
                        class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Go
                        to Leads</button>
                </a>
                {%else%}
                <a href="{% url 'login' %}">
                    <button
                        class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Login
                        to get started</button>
                </a>
                {% endif %}
            </div>
        </div>
    </div>
</section>

{% endblock content %}

templates/navbar.html
<header class="text-gray-600 body-font">

    <div class="container mx-auto flex flex-wrap p-5 flex-col md:flex-row items-center">
        <a href="{% url 'landing-page' %}" class="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
            <svg id="Layer_1" class="w-10 h-10" enable-background="new 0 0 512 512" viewBox="0 0 512 512"
                xmlns="http://www.w3.org/2000/svg">
                <g>
                    <path
                        d="m186.399 126.224 21.036-8.981-.129-28.068-22.222-9.427c-1.83-5.848-4.299-11.552-7.406-17.002l9.004-22.615-20.015-19.837-22.655 9.086c-5.487-3.067-11.226-5.497-17.105-7.291l-9.577-22.089-28.177.015-8.908 21.001c-6.679 1.732-13.168 4.294-19.304 7.688l-20.938-8.344-19.832 19.858 8.483 20.815c-3.375 6.13-5.914 12.607-7.618 19.269l-21.036 8.981.129 28.068 22.222 9.427c1.83 5.848 4.299 11.552 7.406 17.002l-9.004 22.614 20.015 19.837 22.655-9.086c5.487 3.067 11.226 5.497 17.105 7.291l9.577 22.088 28.176-.015 8.908-21.001c6.679-1.731 13.168-4.294 19.304-7.688l20.938 8.344 19.832-19.858-8.483-20.814c3.376-6.129 5.915-12.606 7.619-19.268zm-53.932 4.742c-14.987 15.007-39.399 15.02-54.524.029-15.126-14.991-15.238-39.308-.25-54.315s39.399-15.019 54.524-.029c15.125 14.991 15.238 39.308.25 54.315z"
                        fill="#a6f5cf" />
                    <path
                        d="m186.399 126.224 21.036-8.981-.129-28.068-22.222-9.427c-1.83-5.848-4.299-11.552-7.406-17.002l9.004-22.615-20.015-19.837-22.655 9.086c-5.487-3.067-11.226-5.497-17.105-7.291l-9.577-22.089-28.177.015-5.627 13.266c37.776 13.649 64.775 49.826 64.775 92.31 0 41.563-25.841 77.089-62.334 91.391l4.138 9.544 28.176-.015 8.908-21.001c6.679-1.731 13.168-4.294 19.304-7.688l20.938 8.344 19.832-19.858-8.483-20.815c3.376-6.13 5.915-12.607 7.619-19.269z"
                        fill="#8aedbd" />
                    <g>
                        <g>
                            <path
                                d="m450.55 353.009h-389.1v-211.24c0-11.529 9.346-20.876 20.876-20.876h347.348c11.529 0 20.876 9.346 20.876 20.876z"
                                fill="#6967bf" />
                            <path
                                d="m429.674 120.894h-41.207c11.529 0 20.876 9.346 20.876 20.876v211.24h41.207v-211.24c0-11.53-9.347-20.876-20.876-20.876z"
                                fill="#5b59b2" />
                            <path
                                d="m478.423 391.106h-444.846c-11.529 0-20.876-9.346-20.876-20.876v-17.222h486.598v17.222c0 11.53-9.346 20.876-20.876 20.876z"
                                fill="#7776d0" />
                            <path d="m96.174 155.685h319.651v197.324h-319.651z" fill="#d4d9ff" />
                        </g>
                        <g>
                            <path
                                d="m362.479 312.618h-212.958c-13.11 0-23.738-10.628-23.738-23.738v-68.645c0-13.11 10.628-23.738 23.738-23.738h212.957c13.11 0 23.738 10.628 23.738 23.738v68.645c0 13.11-10.627 23.738-23.737 23.738z"
                                fill="#fff5b5" />
                            <g fill="#7776d0">
                                <path
                                    d="m360.579 282.73-11.221-58.719c-.823-4.041-4.273-7.026-8.389-7.259-4.122-.225-7.883 2.344-9.156 6.266-.029.089-.056.178-.082.268l-10.589 37.146-10.982-37.224c-.027-.093-.056-.186-.088-.277-1.315-3.909-5.095-6.455-9.224-6.169-4.115.278-7.532 3.301-8.326 7.436l-10.578 58.61c-.758 4.199 2.032 8.218 6.231 8.976 4.193.757 8.218-2.032 8.976-6.231l5.804-32.158 9.593 32.515c.027.092.056.184.087.275 1.246 3.709 4.703 6.192 8.613 6.192h.048c3.929-.02 7.382-2.545 8.595-6.282.029-.088.055-.177.081-.266l9.261-32.487 6.171 32.289c.801 4.193 4.857 6.938 9.039 6.139 4.19-.801 6.938-4.848 6.136-9.04z" />
                                <path
                                    d="m213.027 270.237c-3.269-2.743-8.143-2.317-10.885.951-.521.621-1.079 1.198-1.663 1.717-2.994 2.667-6.822 4.019-11.377 4.019-12.333 0-22.366-10.034-22.366-22.367s10.033-22.367 22.366-22.367c4.483 0 8.806 1.319 12.501 3.815 3.536 2.388 8.339 1.459 10.727-2.077s1.459-8.339-2.077-10.727c-6.26-4.228-13.573-6.463-21.151-6.463-20.853 0-37.819 16.966-37.819 37.819s16.966 37.819 37.819 37.819c8.341 0 15.829-2.743 21.652-7.93 1.139-1.013 2.224-2.132 3.225-3.324 2.742-3.268 2.317-8.142-.952-10.885z" />
                                <path
                                    d="m272.8 240.106c0-12.885-10.88-23.368-24.254-23.368h-15.993c-.003 0-.007 0-.01 0s-.007 0-.01 0c-4.268 0-7.726 3.459-7.726 7.726v60.186c0 4.267 3.459 7.726 7.726 7.726s7.726-3.459 7.726-7.726v-16.499l19.014 21.604c1.527 1.735 3.66 2.622 5.803 2.622 1.813 0 3.634-.634 5.102-1.927 3.203-2.819 3.514-7.701.695-10.904l-15.082-17.136c9.846-2.976 17.009-11.849 17.009-22.304zm-24.254 7.916c-1.922 0-5.149.013-8.199.028-.015-2.971-.028-6.092-.028-7.943 0-1.576-.008-4.8-.016-7.915h8.243c4.771 0 8.801 3.625 8.801 7.915s-4.03 7.915-8.801 7.915z" />
                            </g>
                        </g>
                    </g>
                    <g>
                        <path
                            d="m512 383.72c0-42.466-34.94-76.772-77.641-75.738-39.689.961-72.226 32.954-73.819 72.622-.833 20.748 6.693 39.723 19.472 53.864 4.524 5.006 6.955 11.542 6.728 18.29 0 17.935 14.539 32.474 32.474 32.474h34.047c17.935 0 32.474-14.539 32.474-32.474-.15-6.593 2.042-13.146 6.517-18.057 12.264-13.457 19.748-31.34 19.748-50.981z"
                            fill="#ffd54d" />
                        <path
                            d="m512 383.72c0-42.466-34.94-76.772-77.641-75.738-6.448.156-12.708 1.132-18.676 2.826 31.805 8.99 55.11 38.23 55.11 72.912 0 19.641-7.484 37.524-19.746 50.981-4.474 4.91-6.666 11.464-6.517 18.057 0 16.725-12.644 30.497-28.894 32.279 1.176.129 2.37.196 3.58.196h34.047c17.935 0 32.474-14.539 32.474-32.474-.15-6.593 2.042-13.146 6.517-18.057 12.262-13.458 19.746-31.341 19.746-50.982z"
                            fill="#ffc919" />
                        <path
                            d="m450.748 512h-29.019c-7.392 0-13.384-5.992-13.384-13.384 0-7.392 5.992-13.384 13.384-13.384h29.019c7.392 0 13.384 5.992 13.384 13.384 0 7.392-5.992 13.384-13.384 13.384z"
                            fill="#7776d0" />
                        <path
                            d="m443.966 484.489v-70.02h15.56c4.268 0 7.726-3.459 7.726-7.726s-3.459-7.726-7.726-7.726h-46.574c-4.268 0-7.726 3.459-7.726 7.726s3.459 7.726 7.726 7.726h15.561v70.02z"
                            fill="#fff" />
                    </g>
                    <g fill="#e8f3ff">
                        <path
                            d="m345.265 466.878c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.265 0-7.726-3.461-7.726-7.726zm-41.208 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.264 0-7.726-3.461-7.726-7.726zm-41.207 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.264 0-7.726-3.461-7.726-7.726zm-41.207 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.264 0-7.726-3.461-7.726-7.726zm-41.207 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.265 0-7.726-3.461-7.726-7.726zm-41.208 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.264 0-7.726-3.461-7.726-7.726zm-41.207 0c0-4.275 3.462-7.726 7.726-7.726 4.266 0 7.726 3.451 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.264 0-7.726-3.461-7.726-7.726zm-2.029-39.178c0-4.275 3.462-7.726 7.726-7.726 4.265 0 7.726 3.451 7.726 7.726 0 4.265-3.462 7.726-7.726 7.726-4.264.001-7.726-3.461-7.726-7.726z" />
                        <path
                            d="m430.069 83.754c0-4.265 3.451-7.726 7.726-7.726 4.265 0 7.726 3.461 7.726 7.726 0 4.265-3.462 7.726-7.726 7.726-4.275 0-7.726-3.461-7.726-7.726zm-2.266-38.941c0-4.265 3.452-7.726 7.726-7.726 4.266 0 7.726 3.461 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.274 0-7.726-3.462-7.726-7.726zm-41.207 0c0-4.265 3.452-7.726 7.726-7.726 4.266 0 7.726 3.461 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.275 0-7.726-3.462-7.726-7.726zm-41.208 0c0-4.265 3.452-7.726 7.726-7.726 4.266 0 7.726 3.461 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.274 0-7.726-3.462-7.726-7.726zm-41.207 0c0-4.265 3.452-7.726 7.716-7.726 4.276 0 7.736 3.461 7.736 7.726 0 4.265-3.461 7.726-7.736 7.726-4.264 0-7.716-3.462-7.716-7.726zm-41.207 0c0-4.265 3.452-7.726 7.726-7.726 4.266 0 7.726 3.461 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.274 0-7.726-3.462-7.726-7.726zm-41.207 0c0-4.265 3.452-7.726 7.726-7.726 4.266 0 7.726 3.461 7.726 7.726 0 4.265-3.461 7.726-7.726 7.726-4.275 0-7.726-3.462-7.726-7.726z" />
                    </g>
                </g>
            </svg>
            <span class="ml-3 text-xl">DJ CRM</span>
        </a>

        <nav class="md:ml-auto flex flex-wrap items-center text-base justify-center">
            {% if not request.user.is_authenticated %}
            <a href="{% url 'signup' %}">
                <button
                    class="inline-flex items-center bg-gray-100 mr-5 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 hover:text-indigo-500 rounded text-base mt-4 md:mt-0 bg-indigo-500 text-white">Sign
                    up
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                        stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                </button>
            </a>
            {%else%}
            <a href="{% url 'leads:lead-list' %}" class="mr-5 hover:text-blue">Leads</a>
            {% if request.user.is_organizer %}
            <a href="{% url 'agents:agent-list' %}" class="mr-5 hover:text-blue">Agents</a>
            {% endif %}
            {% endif %}
            {% if request.user.is_authenticated %}

            You are logged in as&nbsp;

            <h1 class="font-bold"> {{request.user.username}} </h1>

            <a href="{% url 'logout' %}">
                <button
                    class=" ml-3 inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Logout
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                        stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                </button>
            </a>
            {% else %}
            <a href="{% url 'login' %}">
                <button
                    class="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 md:mt-0">Login
                    <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round"
                        stroke-width="2" class="w-4 h-4 ml-1" viewBox="0 0 24 24">
                        <path d="M5 12h14M12 5l7 7-7 7"></path>
                    </svg>
                </button>
            </a>
            {% endif %}
        </nav>
    </div>

</header>